spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scholara
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
server:
  port: 8080
jwt:
  secret: myjwtsecret
  expiration: 3600000 # 1 hour in milliseconds